### ISSUE TITLE
Newly created user should have site:user role automatically

### ISSUE THREAD

**Issue by afrastgeek** [gamantha/ats-admin#11]
Ketika user dibuat dari CRUD ~~Profile~~ User, user tersebut harus langsung mendapat role `site:user` secara otomatis.

**Comment by afrastgeek** [comment]
@mazsam saya ada salah sebut crud. seharusnya crud user, bukan crud profile.

**Comment by mazsam** [comment]
Iya mas, itu sudah. ketika user baru dibuat otomatis create rolenya. cuma tadi langsung ke commit jadi satu. di https://github.com/gamantha/ats-admin/pull/16/commits/2e93355fed8ec8ddf40676ceadf5cf60aaa650bc
